services:
  backend:
    build: .
    ports:
      - "5000:5000" # Map your PC's port 5000 to the container's port 5000
    env_file:
      - ./.env # This injects all your secrets (MONGO_URI, JWT_SECRET, etc.)
    volumes:
      - .:/app # Syncs your local code with the code in the container
      - /app/node_modules # Prevents local node_modules from overwriting the container's
    command: npm run dev # For development, we override the CMD to run in dev mode